/*
 * Copyright (c) 2020, 2024, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.AivisionService.Models
{
    /// <summary>
    /// A sequence of frames that was (or appears to be) continuously captured for a label/object/text?.
    /// </summary>
    public class VideoSegment 
    {
        
        /// <value>
        /// Video start time offset(Milliseconds).
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "StartTimeOffsetMs is required.")]
        [JsonProperty(PropertyName = "startTimeOffsetMs")]
        public System.Nullable<int> StartTimeOffsetMs { get; set; }
        
        /// <value>
        /// Video end time offset(Milliseconds).
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "EndTimeOffsetMs is required.")]
        [JsonProperty(PropertyName = "endTimeOffsetMs")]
        public System.Nullable<int> EndTimeOffsetMs { get; set; }
        
    }
}
