/*
 * Copyright (c) 2020, 2023, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.NetworkfirewallService.Models
{
    /// <summary>
    /// List of addresses with a reference name.
    /// The value of an entry is a list of IP addresses or prefixes in CIDR notation or FQDNs.
    /// The associated key is the identifier by which the IP address list is referenced.
    /// 
    /// </summary>
    public class AddressList 
    {
        
        /// <value>
        /// Unique name to identify the group of addresses to be used in the policy rules.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Name is required.")]
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }
        
        /// <value>
        /// Type of address List. The accepted values are - * FQDN * IP
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Type is required.")]
        [JsonProperty(PropertyName = "type")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<AddressListType> Type { get; set; }
        
        /// <value>
        /// List of addresses.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Addresses is required.")]
        [JsonProperty(PropertyName = "addresses")]
        public System.Collections.Generic.List<string> Addresses { get; set; }
        
        /// <value>
        /// Count of total Addresses in the AddressList
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "TotalAddresses is required.")]
        [JsonProperty(PropertyName = "totalAddresses")]
        public System.Nullable<int> TotalAddresses { get; set; }
        
        /// <value>
        /// OCID of the Network Firewall Policy this Address List belongs to.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "ParentResourceId is required.")]
        [JsonProperty(PropertyName = "parentResourceId")]
        public string ParentResourceId { get; set; }
        
    }
}
