/*
 * Copyright (c) 2020, 2024, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.OpsiService.Models
{
    /// <summary>
    /// Contains CPU recommendation.
    /// 
    /// </summary>
    public class HostCpuRecommendations : HostInsightHostRecommendations
    {
                ///
        /// <value>
        /// Show if OPSI recommend to convert an instance to a burstable instance and show recommended cpu baseline if positive recommendation.
        /// </value>
        ///
        public enum BurstableEnum {
            /// This value is used if a service returns a value for this enum that is not recognized by this version of the SDK.
            [EnumMember(Value = null)]
            UnknownEnumValue,
            [EnumMember(Value = "BASELINE_1_8")]
            Baseline18,
            [EnumMember(Value = "BASELINE_1_2")]
            Baseline12,
            [EnumMember(Value = "NO_RECOMMENDATION")]
            NoRecommendation,
            [EnumMember(Value = "DISABLE_BURSTABLE")]
            DisableBurstable
        };

        /// <value>
        /// Show if OPSI recommend to convert an instance to a burstable instance and show recommended cpu baseline if positive recommendation.
        /// </value>
        [JsonProperty(PropertyName = "burstable")]
        [JsonConverter(typeof(Oci.Common.Utils.ResponseEnumConverter))]
        public System.Nullable<BurstableEnum> Burstable { get; set; }
        
        [JsonProperty(PropertyName = "metricRecommendationName")]
        private readonly string metricRecommendationName = "HOST_CPU_RECOMMENDATIONS";
    }
}
