/*
 * Copyright (c) 2020, 2024, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.OpsiService.Models
{
    /// <summary>
    /// SQL Response time distribution entry.
    /// </summary>
    public class SqlResponseTimeDistributionAggregation 
    {
        
        /// <value>
        /// Response time bucket id
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "BucketId is required.")]
        [JsonProperty(PropertyName = "bucketId")]
        public string BucketId { get; set; }
        
        /// <value>
        /// Total number of SQL executions
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "ExecutionsCount is required.")]
        [JsonProperty(PropertyName = "executionsCount")]
        public System.Nullable<long> ExecutionsCount { get; set; }
        
    }
}
