/*
 * Copyright (c) 2020, 2023, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.CloudbridgeService.Models
{
    /// <summary>
    /// The result of an analytics aggregation on a set of assets.
    /// </summary>
    public class AssetAggregation 
    {
        
        /// <value>
        /// The dimensions along which assets can be aggregated for analytics.
        /// </value>
        [JsonProperty(PropertyName = "dimensions")]
        public System.Collections.Generic.Dictionary<string, string> Dimensions { get; set; }
        
        /// <value>
        /// Returns the total number of observations from the group of assets.
        /// </value>
        [JsonProperty(PropertyName = "count")]
        public System.Nullable<long> Count { get; set; }
        
        /// <value>
        /// Returns the highest value from all the assets.
        /// </value>
        [JsonProperty(PropertyName = "max")]
        public System.Double Max { get; set; }
        
        /// <value>
        /// Returns the value of sum divided by count from the group of assets.
        /// </value>
        [JsonProperty(PropertyName = "mean")]
        public System.Double Mean { get; set; }
        
        /// <value>
        /// Returns the lowest value from the group of assets.
        /// </value>
        [JsonProperty(PropertyName = "min")]
        public System.Double Min { get; set; }
        
        /// <value>
        /// Returns all values added together from the group of assets.
        /// </value>
        [JsonProperty(PropertyName = "sum")]
        public System.Double Sum { get; set; }
        
        /// <value>
        /// Aggregated property.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "AggregatedProperty is required.")]
        [JsonProperty(PropertyName = "aggregatedProperty")]
        public string AggregatedProperty { get; set; }
        
    }
}
