/*
 * Copyright (c) 2020, 2022, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace Oci.OperatoraccesscontrolService.Models
{
  /// <summary>
  /// Possible lifecycle states for an access request.
  /// </summary>
  public enum AccessRequestLifecycleStates {
      [EnumMember(Value = "CREATED")]
      Created,
      [EnumMember(Value = "APPROVALWAITING")]
      Approvalwaiting,
      [EnumMember(Value = "PREAPPROVED")]
      Preapproved,
      [EnumMember(Value = "APPROVED")]
      Approved,
      [EnumMember(Value = "MOREINFO")]
      Moreinfo,
      [EnumMember(Value = "REJECTED")]
      Rejected,
      [EnumMember(Value = "DEPLOYED")]
      Deployed,
      [EnumMember(Value = "DEPLOYFAILED")]
      Deployfailed,
      [EnumMember(Value = "UNDEPLOYED")]
      Undeployed,
      [EnumMember(Value = "UNDEPLOYFAILED")]
      Undeployfailed,
      [EnumMember(Value = "CLOSEFAILED")]
      Closefailed,
      [EnumMember(Value = "REVOKEFAILED")]
      Revokefailed,
      [EnumMember(Value = "EXPIRYFAILED")]
      Expiryfailed,
      [EnumMember(Value = "REVOKING")]
      Revoking,
      [EnumMember(Value = "REVOKED")]
      Revoked,
      [EnumMember(Value = "EXTENDING")]
      Extending,
      [EnumMember(Value = "EXTENDED")]
      Extended,
      [EnumMember(Value = "EXTENSIONREJECTED")]
      Extensionrejected,
      [EnumMember(Value = "COMPLETING")]
      Completing,
      [EnumMember(Value = "COMPLETED")]
      Completed,
      [EnumMember(Value = "EXPIRED")]
      Expired,
      [EnumMember(Value = "APPROVEDFORFUTURE")]
      Approvedforfuture,
      [EnumMember(Value = "INREVIEW")]
      Inreview
  }
}
