/*
 * Copyright (c) 2020, 2023, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.QueueService.Models
{
    /// <summary>
    /// The response to a UpdateMessages request. It indicates the number of server and client failures as well as an array of entries for successful and failed actions.
    /// </summary>
    public class UpdateMessagesResult 
    {
        
        /// <value>
        /// The number of messages that failed to be updated in the queue because of a server failure.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "ServerFailures is required.")]
        [JsonProperty(PropertyName = "serverFailures")]
        public System.Nullable<int> ServerFailures { get; set; }
        
        /// <value>
        /// The number of messages that failed to be updated in the queue because of a client failure such as an invalid receipt or invalid visibilityInSeconds.
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "ClientFailures is required.")]
        [JsonProperty(PropertyName = "clientFailures")]
        public System.Nullable<int> ClientFailures { get; set; }
        
        /// <value>
        /// An array of items representing the result of each action.
        /// The order is guaranteed to be the same as in the `UpdateMessagesDetails` object.
        /// If a message was successfully updated in the queue, the entry includes the `id` and `visibleAfter` fields.
        /// If a message failed to be updated in the queue, the entry includes the `errorCode` and `errorMessage` fields.
        /// 
        /// </value>
        /// <remarks>
        /// Required
        /// </remarks>
        [Required(ErrorMessage = "Entries is required.")]
        [JsonProperty(PropertyName = "entries")]
        public System.Collections.Generic.List<UpdateMessagesResultEntry> Entries { get; set; }
        
    }
}
