/*
 * Copyright (c) 2020, 2026, Oracle and/or its affiliates. All rights reserved.
 * This software is dual-licensed to you under the Universal Permissive License (UPL) 1.0 as shown at https://oss.oracle.com/licenses/upl or Apache License 2.0 as shown at http://www.apache.org/licenses/LICENSE-2.0. You may choose either license.
 */

// NOTE: Code generated by OracleSDKGenerator.
// DO NOT EDIT this file manually.


using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;


namespace Oci.CloudmigrationsService.Models
{
    /// <summary>
    /// Error Handling in OLVM
    /// </summary>
    public class OlvmErrorHandling 
    {
                ///
        /// <value>
        /// Migrate on error
        /// </value>
        ///
        public enum OnErrorEnum {
            [EnumMember(Value = "DO_NOT_MIGRATE")]
            DoNotMigrate,
            [EnumMember(Value = "MIGRATE")]
            Migrate,
            [EnumMember(Value = "MIGRATE_HIGHLY_AVAILABLE")]
            MigrateHighlyAvailable
        };

        /// <value>
        /// Migrate on error
        /// </value>
        [JsonProperty(PropertyName = "onError")]
        [JsonConverter(typeof(StringEnumConverter))]
        public System.Nullable<OnErrorEnum> OnError { get; set; }
        
    }
}
